//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vial3._1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vialcatEntities : DbContext
    {
        public vialcatEntities()
            : base("name=vialcatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<vial_afiliados> vial_afiliados { get; set; }
        public virtual DbSet<vial_estadoafiliacion> vial_estadoafiliacion { get; set; }
        public virtual DbSet<vial_usuarioscomercio> vial_usuarioscomercio { get; set; }
        public virtual DbSet<vial_comercio> vial_comercio { get; set; }
        public virtual DbSet<vial_ordencomprapresentada> vial_ordencomprapresentada { get; set; }
        public virtual DbSet<vial_estadoordencompra> vial_estadoordencompra { get; set; }
        public virtual DbSet<vial_ordendecompra> vial_ordendecompra { get; set; }
    }
}
