//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vial3._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vial_usuarioscomercio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vial_usuarioscomercio()
        {
            this.vial_ordencomprapresentada = new HashSet<vial_ordencomprapresentada>();
        }
    
        public int idUsuariosComercio { get; set; }
        public int idComercio { get; set; }
        public string usuario { get; set; }
        public string contrasenial { get; set; }
    
        public virtual vial_comercio vial_comercio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vial_ordencomprapresentada> vial_ordencomprapresentada { get; set; }
    }
}
