//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vial3._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vial_afiliados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vial_afiliados()
        {
            this.vial_ordendecompra = new HashSet<vial_ordendecompra>();
        }
    
        public int idAfiliados { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public int documento { get; set; }
        public string domicilio { get; set; }
        public string telefono { get; set; }
        public Nullable<int> estado_afiliacion { get; set; }
    
        public virtual vial_estadoafiliacion vial_estadoafiliacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vial_ordendecompra> vial_ordendecompra { get; set; }
    }
}
