//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vial3._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vial_ordencomprapresentada
    {
        public int idordencomprapresentada { get; set; }
        public int idcomercio { get; set; }
        public int idordendecompra { get; set; }
        public System.DateTime fechapresentacion { get; set; }
        public Nullable<int> usuario { get; set; }
        public string ip { get; set; }
    
        public virtual vial_comercio vial_comercio { get; set; }
        public virtual vial_usuarioscomercio vial_usuarioscomercio { get; set; }
        public virtual vial_ordendecompra vial_ordendecompra { get; set; }
    }
}
