//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vial3._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vial_comercio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vial_comercio()
        {
            this.vial_usuarioscomercio = new HashSet<vial_usuarioscomercio>();
            this.vial_ordencomprapresentada = new HashSet<vial_ordencomprapresentada>();
            this.vial_ordendecompra = new HashSet<vial_ordendecompra>();
        }
    
        public int id_comercio { get; set; }
        public string razonsocial { get; set; }
        public string domicilio { get; set; }
        public string telefono { get; set; }
        public string cuit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vial_usuarioscomercio> vial_usuarioscomercio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vial_ordencomprapresentada> vial_ordencomprapresentada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vial_ordendecompra> vial_ordendecompra { get; set; }
    }
}
