//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vial3._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vial_estadoafiliacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vial_estadoafiliacion()
        {
            this.vial_afiliados = new HashSet<vial_afiliados>();
        }
    
        public int idestadoafiliacion { get; set; }
        public string estadoafiliacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vial_afiliados> vial_afiliados { get; set; }
    }
}
