//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vial3._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vialcomercio
    {
        public int idcomercio { get; set; }
        public string nombre { get; set; }
        public string razonsocial { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string cuit { get; set; }
        public int vialafiliados_idAfiliado { get; set; }
    }
}
